[package]
name = "knot"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
ratatui = "0.25"
clap = { version = "4.4", features = ["derive"] }
crossterm = "0.27"
dirs = "5.0"

walkdir = "2.4"
